[tool.poetry]
name = "shapesynthesis"
version = "0.1.0"
description = "Topological shape synthesis"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "kaolin-source"
priority = "explicit"
url = "https://nvidia-kaolin.s3.us-east-2.amazonaws.com/index.html"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
torch = "^2.5.1"
lightning = "^2.4.0"
torch-geometric = "^2.6.1"
torchvision = "^0.20.1"
kaolin = {url = "https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124/kaolin-0.17.0-cp312-cp312-linux_x86_64.whl"}
tensorboard = "^2.18.0"
tensorboardx = "^2.6.2.2"
emd-ext = {path = "shapesynthesis/metrics/PyTorchEMD/emd_ext-0.0.0-cp310-cp310-linux_x86_64.whl"}
chamfer-3d = {path = "shapesynthesis/metrics/ChamferDistancePytorch/chamfer3D/chamfer_3D-0.0.0-cp310-cp310-linux_x86_64.whl"}

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.25.0"


[tool.poe.tasks]
torch-cuda = "python -m pip install torch torchvision torchaudio"
torch-cpu      = "python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu"
pyg-cpu        = "pip install torch_geometric"
lightning      = "python -m pip install lightning"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"




