[project]
name = "dependencies"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "torch==2.5.1",
    "setuptools==80.7.1",
    "ninja>=1.13.0",
    "numpy>=2.2.6",
]

