ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 256
  resolution: 256 
  scale: 128
  r: 4.5
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

ectrenderconfig: &ref-ectrenderconfig
  seed: 2024
  num_thetas: 128
  resolution: 128
  scale: 32
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True


data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - airplane
  num_workers: 0 # Only for ubuntu.
  batch_size: 32
  pin_memory: True
  num_pts: 2048
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

render: 
  num_pts: 2048
  num_epochs: 2000
  ectconfig: *ref-ectrenderconfig
  dataset_name: airplane
  experiment_name: ect_128