model:
  hidden_size: 512
  num_pts: 128
  num_dims: 2
  learning_rate: 0.0005
  save_name: "ectencoder_dsprites.ckpt" 

data:
  root: ./data/dsprites
  module: datasets.dsprites
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False

layer: 
  ect_size: 64
  dim: 2

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1


loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs