
model:
  in_channels: 1
  latent_dim: 64
  save_name: "vae_shapenet.ckpt"


trainer:
  accelerator: auto
  max_epochs: 1
  log_every_n_steps: 1
litmodel:
  learning_rate: 0.001

data: 
  module: datasets.shapenet
  root: ./data/shapenet
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  samplepoints: 2048

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

layer: 
  ect_size: 96
  dim: 3