
model:
  in_channels: 1
  latent_dim: 64
  save_name: "vae_dsprites.ckpt"

data:
  root: ./data/dsprites
  module: datasets.dsprites
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False

layer: 
  ect_size: 64
  dim: 2

trainer:
  accelerator: auto
  max_epochs: 500
  log_every_n_steps: 1

litmodel:
  learning_rate: 0.001

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs
