
vaeconfig:
  in_channels: 1
  latent_dim: 64
  img_size: 64
  save_name: "vae_mnist.ckpt"

data: 
  module: datasets.mnist
  root: "./data/mnistpointcloud"
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False


ectconfig: 
  num_dims: 2
  num_thetas: 64
  bump_steps: 64
  r: 1.1
  ect_type: "points"
  device: "cuda:0"
  num_features: 2
  normalized: True

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1
  learning_rate: 0.001
  save_dir: ./trained_models 
  save_name: vae_mnist
  experimentname: vae_mnist


loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs
