
vaeconfig:
  in_channels: 1
  latent_dim: 256
  img_size: 96
  save_name: "vae_shapenet_airplane.ckpt"


trainer:
  accelerator: auto
  max_epochs: 1000
  log_every_n_steps: 1
  learning_rate: 0.0005
  save_dir: ./trained_models 
  save_name: vae_shapenet_airplane
  experimentname: vae_airplane

data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - airplane
  num_workers: 0
  batch_size: 32
  pin_memory: True
  drop_last: False


loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

ectconfig: 
  num_dims: 3
  num_thetas: 96
  bump_steps: 96
  r: 7 
  ect_type: "points"
  device: "cuda:0"
  num_features: 3
  normalized: True
