

data: 
  module: datasets.mnist
  root: "./data/mnistpointcloud"
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False

modelconfig:
  module: models.encoder
  hidden_size: 512
  num_pts: 128
  num_dims: 2
  learning_rate: 0.001
  ectlossconfig: 
    dim: 2
    num_thetas: 64
    bump_steps: 64  
    r: 1.1
    ect_type: "points"
    num_features: 2
    normalized: True
  ectconfig: 
    dim: 2
    num_thetas: 64
    bump_steps: 64  
    r: 1.1
    ect_type: "points"
    device: "cuda:0"
    num_features: 2
    normalized: True

loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1
  save_dir: "trained_models" 
  model_name: "encoder_mnist.ckpt" 
  experiment_name: "encoder_mnist"