modelconfig:
  hidden_size: 512
  num_pts: 2048
  num_dims: 3
  learning_rate: 0.0005
  save_name: "ectencoder_shapenet_chair_sparse.ckpt" 

data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - chair
  num_workers: 0
  batch_size: 4
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: 
    dim: 3
    num_thetas: 256
    bump_steps: 256 
    r: 5
    ect_type: "points"
    device: "cuda:0"
    num_features: 3
    normalized: True
    

ectlossconfig: 
  dim: 3
  num_thetas: 256
  bump_steps: 256 
  r: 5
  ect_type: "points"
  device: "cuda:0"
  num_features: 3
  normalized: True


ectconfig: 
  dim: 3
  num_thetas: 256
  bump_steps: 256 
  r: 5
  ect_type: "points"
  device: "cuda:0"
  num_features: 3
  normalized: True
  


loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs

trainer:
  accelerator: auto
  max_epochs: 400
  log_every_n_steps: 1
  save_dir: "trained_models" 
  save_name: "ectencoder_shapenet_chair_sparse" 
  experimentname: "ectencoder_shapenet_chair_sparse"