model:
  hidden_size: 2048
  num_pts: 2048
  num_dims: 3
  learning_rate: 0.0001
  save_name: "ectencoder_shapenet_airplane_scaled.ckpt" 

layer: 
  ect_size: 96
  dim: 3
  r: 7

data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - airplane
  num_workers: 0
  batch_size: 16 
  pin_memory: True
  drop_last: False

trainer:
  accelerator: auto
  max_epochs: 50
  log_every_n_steps: 1

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

