model:
  hidden_size: 4096
  num_pts: 1024
  num_dims: 3
  learning_rate: 0.0005
  save_name: "ectencoder_topological.ckpt" 

data:
  root: ./data
  module: datasets.topological
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  n_samples: 1024
  n_manifolds: 1000

layer: 
  ect_size: 96
  dim: 3

trainer:
  accelerator: auto
  max_epochs: 500
  log_every_n_steps: 1

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs