model:
  hidden_size: 2048
  num_pts: 2048
  num_dims: 3
  learning_rate: 0.0005
  save_name: "ectencoder_modelnet.ckpt" 

layer: 
  ect_size: 96
  dim: 3

data: 
  module: datasets.modelnet
  name: "40"
  root: ./data/modelnet
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  samplepoints: 1024

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

