
model:
  in_channels: 1
  latent_dim: 64
  save_name: "vae_mnist.ckpt"

layer: 
  ect_size: 64

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1

litmodel:
  learning_rate: 0.001

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs
