#
# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 128
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

ectlossconfig: &ref-ectlossconfig 
  num_thetas: 128
  resolution: 128
  scale: 8
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  seed: 2024

transform: 
  module: transforms.ecttransform
  ectconfig: *ref-ectconfig

data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 32
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

trainer: &ref-trainer
  module: trainer
  seed : 1111
  max_epochs: 10 # Should be 20k
  log_every_n_steps: 1
  accelerator: auto
  precision: null
  checkpoint_interval: 20

modelconfig:
  module: models.encoder_attn
  num_pts: 2048
  learning_rate: 0.001
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig
  down_channels : [64,  128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, True, True]
  attn_down : [False, False,True]
  norm_channels: 1
  im_channels : 1
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

logger:
  module: loggers.wandblogger
  project: shape-synthesis
  entity: aidos-labs
  trainconfig: *ref-trainer
  results_dir: encoder_attn_airplane

