#
# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 128
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

ectlossconfig: &ref-ectlossconfig 
  num_thetas: 128
  resolution: 128
  scale: 8
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  seed: 2024

transform: 
  module: transforms.ecttransform
  ectconfig: *ref-ectconfig

data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

trainer: &ref-trainer
  module: trainer
  seed : 1111
  max_epochs: 500 
  log_every_n_steps: 1
  accelerator: auto
  precision: null
  checkpoint_interval: 200

modelconfig:
  module: models.encoder_exp
  num_pts: 2048
  #learning_rate: 0.001
  learning_rate: 0.001
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig

logger:
  module: loggers.wandblogger
  project: shape-synthesis
  entity: aidos-labs
  trainconfig: *ref-trainer
  results_dir: encoder_exp_airplane
