#
# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 128
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

ectlossconfig: &ref-ectlossconfig 
  num_thetas: 128
  resolution: 128
  scale: 8
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  seed: 2024

transform: 
  - module: transforms.rotate
    axis: 1
    max_degrees: 180 


data: 
  module: datasets.mnist3d
  root_dir: ./data/mnist3d
  raw_dir: ./data/raw/mnist3d
  num_workers: 2
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

trainer: &ref-trainer
  module: trainer
  seed : 1111
  max_epochs: 1000 # Should be 20k
  log_every_n_steps: 1
  accelerator: auto
  precision: null
  checkpoint_interval: 100

modelconfig:
  module: models.encoder
  num_pts: 2048
  learning_rate: 0.0001
  ectlossconfig: *ref-ectlossconfig
  ectconfig: *ref-ectconfig

logger:
  module: loggers.wandblogger
  project: shape-synthesis
  entity: aidos-labs
  trainconfig: *ref-trainer
  results_dir: encoder_airplane


# trainer:
#   accelerator: auto
#   max_epochs: 5000
#   log_every_n_steps: 5
#   save_dir: trained_models
#   model_name: encoder_new_airplane.ckpt
#   results_dir: ./results
