ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 500
  r: 1
  ect_type: "points"
  ambient_dimension: 2
  normalized: True

data: 
  module: datasets.mnist
  root: ./data
  num_workers: 0
  batch_size: 128
  num_pts: 256
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

modelconfig:
  module: models.vae_baseline_sampling
  latent_dim: 64
  beta_min: 0.00000001
  beta_max: 0.001
  beta_period: 200
  learning_rate: 0.001
  ectconfig: *ref-ectconfig 

trainer:
  accelerator: auto
  max_epochs: 50 # Was 1000 before.
  log_every_n_steps: 1
  save_dir: ./trained_models 
  model_name: vae_mnist.ckpt
  results_dir: ./results

loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "vae_mnist"
  tags: []
