# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 32
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

modelconfig:
  module: models.vae_new_1d
  # in_channels: 1
  latent_dim: 128
  beta_min: 0.00000001
  beta_max: 0.001
  beta_period: 400
  learning_rate: 0.0001
  ectconfig: *ref-ectconfig 

trainer:
  accelerator: auto
  max_epochs: 1000 # Was 1000 before.
  log_every_n_steps: 1
  save_dir: ./trained_models 
  model_name: vae_new_airplane.ckpt
  results_dir: ./results

loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "vae_new_airplane"
  tags: []
