# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128 
  scale: 32
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

modelconfig:
  module: models.vae_sigma
  ectconfig: *ref-ectconfig

trainer:
  accelerator: auto
  max_epochs: 10
  log_every_n_steps: 1
  save_dir: ./trained_models 
  model_name: vae_sigma_airplane.ckpt
  results_dir: ./results

loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "vae_sigma_airplane"
  tags: []
