ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 128
  resolution: 128
  scale: 100
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True


data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 32
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

transform: 
  module: transforms.ecttransform
  seed: 2024
  num_thetas: 128
  resolution: 128
  scale: 100
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True
  structured: False


trainer: &ref-trainer
  module: trainer
  seed : 1111
  max_epochs: 100 # Should be 20k
  log_every_n_steps: 1
  accelerator: auto
  precision: null
  checkpoint_interval: 10


logger:
  module: loggers.wandblogger
  project: shape-synthesis
  entity: aidos-labs
  trainconfig: *ref-trainer
  results_dir: vae_baseline_airplane


modelconfig:
  module: models.vae_baseline
  im_channels: 1
  lr: 0.0001
  ectconfig: *ref-ectconfig
  latent_dim: 64
  beta_min: 0.00000001
  beta_max: 0.001
  beta_period: 400
  perceptual_weight: 1
  learning_rate: 0.0001
  disc_start: 1000
  disc_weight: 0.01
