ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 64
  resolution: 64
  scale: 128
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True


data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 32
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig


# trainer: 
#   seed : 1111
#   checkpoint_dir: trained_models
#   vqvae_checkpoint: vqvae.ckpt
#   checkpoint_interval: 20
#   log_dir: logs
#   precision: 16-mixed
#   accelerator: cuda
#   epochs : 100
#   lr: 0.0001


modelconfig:
  z_channels: 9
  codebook_size : 1024
  down_channels : [64,  128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, False, False]
  attn_down : [False, False,False]
  norm_channels: 32
  im_channels : 1
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

discriminator:
  im_channels: 1

train:
  disc_start: 1000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  ldm_lr: 0.00001
  ldm_epochs : 200
  perceptual_weight: 1
  kl_weight: 0.000005
  save_latents : False
