ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 32
  resolution: 32
  scale: 128
  r: 7
  ect_type: "points"
  ambient_dimension: 3
  normalized: True


data: 
  module: datasets.shapenet
  root_dir: ./data/shapenet
  raw_dir: ./data/shapenet/raw/ShapeNetCore.v2.PC15k
  cates: 
    - airplane
  num_workers: 0
  batch_size: 32
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

trainer: 
  seed : 1111
  max_epochs: 5 # Should be 20k
  log_every_n_steps: 1
  model_name: vae_resnet_airplane.ckpt
  results_dir: ./results
  accelerator: auto

modelconfig:
  module: models.vqvae
  lr: 0.0001
  ectconfig: *ref-ectconfig
  z_channels: 9
  codebook_size : 1024
  down_channels : [64,  128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, False, False]
  attn_down : [False, False,False]
  norm_channels: 32
  im_channels : 1
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  disc_start: 1000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  kl_weight: 0.000005
  save_latents : False


loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-lab
  save_dir: ./lightning_logs
  experiment_name: "vqvae_airplane"
  tags: []


