model:
  hidden_size: 2048
  num_pts: 2048
  num_dims: 3
  learning_rate: 0.001
  save_name: "ectencoder_shapenet_airplane_scaled.ckpt" 

layer: 
  ect_size: 96
  dim: 3

data: 
  module: datasets.shapenet
  root: ./data/shapenet
  categories: 
    - airplane
  num_workers: 0
  batch_size: 32 
  pin_memory: False
  drop_last: False

trainer:
  accelerator: auto
  max_epochs: 50
  log_every_n_steps: 1
  save_dir: "trained_models" 
  save_name: "ectencoder_shapenet_airplane_scaled" 
  experimentname: "encoder_shapenet_airplane_scaled"

loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

