
vaeconfig:
  in_channels: 1
  latent_dim: 64
  img_size: 96
  save_name: "vae_topological.ckpt"

data:
  root: ./data
  module: datasets.topological
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  n_samples: 1024
  n_manifolds: 1000

trainer:
  accelerator: auto
  max_epochs: 100
  log_every_n_steps: 1
  learning_rate: 0.001
  log_every_n_steps: 1
  save_dir: ./trained_models 
  save_name: vae_topological
  experimentname: vae_topological


loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs


ectconfig: 
  num_dims: 3
  num_thetas: 96
  bump_steps: 96
  r: 1.1
  ect_type: "points"
  device: "cuda:0"
  num_features: 3
  normalized: True