modelconfig:
  hidden_size: 2048
  num_pts: 2048
  num_dims: 3
  learning_rate: 0.0001

ectconfig: 
  dim: 3
  num_thetas: 96
  bump_steps: 96
  r: 4.5
  ect_type: "points"
  device: "cuda:0"
  num_features: 3
  normalized: True


ectlossconfig: 
  dim: 3
  num_thetas: 8
  bump_steps: 256
  r: 4.5
  ect_type: "points_derivative"
  device: "cuda:0"
  num_features: 3
  normalized: False


data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - car
  num_workers: 4
  batch_size: 32
  pin_memory: False
  drop_last: False

trainer:
  accelerator: auto
  max_epochs: 1000
  log_every_n_steps: 1
  save_dir: "trained_models" 
  save_name: "ectencoder_shapenet_car" 
  experimentname: "encoder_shapenet_car"


loggers: 
  project: "toporecon-dev"
  entity: aidos-labs
  save_dir: ./lightning_logs

