modelconfig:
  hidden_size: 512
  num_pts: 128
  num_dims: 2
  learning_rate: 0.001
  save_name: "ectencoder_mnist.ckpt" 

data: 
  module: datasets.mnist
  root: "./data/mnistpointcloud"
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False

ectlossconfig: 
  dim: 2
  num_thetas: 128
  bump_steps: 128 
  r: 1.1
  ect_type: "points"
  device: "cuda:0"
  num_features: 2
  normalized: True


ectconfig: 
  dim: 2
  num_thetas: 256
  bump_steps: 256 
  r: 1.1
  ect_type: "points"
  device: "cuda:0"
  num_features: 2
  normalized: True


loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs

trainer:
  accelerator: auto
  max_epochs: 400
  log_every_n_steps: 1
  save_dir: "trained_models" 
  save_name: "ectencoder_mnist_sparse" 
  experimentname: "encoder_mnist_sparse"