# Global ect config, referenced in modelconfig.
ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 64
  resolution: 128 
  scale: 64
  r: 1.1
  ect_type: "points"
  ambient_dimension: 2
  normalized: True

ectlossconfig: &ref-ectlossconfig 
    num_thetas: 64
    resolution: 64  
    scale: 32
    r: 1.1
    ect_type: "points"
    ambient_dimension: 2
    normalized: True
    seed: 2024

data: 
  module: datasets.mnist
  root: "./data/mnistpointcloud"
  num_workers: 0
  num_pts: 128
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

modelconfig:
  module: models.encoder
  num_pts: 16
  learning_rate: 0.001
  ectconfig: *ref-ectconfig 
  ectlossconfig: *ref-ectlossconfig
  
  
loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "encoder_mnist_downsample"
  tags: []

trainer:
  accelerator: auto
  max_epochs: 10
  log_every_n_steps: 1
  save_dir: "trained_models" 
  model_name: "encoder_mnist_downsample.ckpt" 
  
