data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - airplane
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: 
    seed: 2024
    num_thetas: 256
    bump_steps: 256 
    r: 7
    ect_type: "points"
    num_features: 3
    normalized: True

modelconfig:
  module: models.encoder
  num_pts: 2048
  learning_rate: 0.00005
  ectlossconfig: 
    seed: 2024
    num_thetas: 64
    bump_steps: 64 
    r: 7
    ect_type: "points"
    num_features: 3 
    normalized: True


loggers: 
  project: toporecon-dev
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "encoder_airplane"

trainer:
  accelerator: auto
  max_epochs: 200
  log_every_n_steps: 1
  save_dir: "trained_models" 
  model_name: "encoder_airplane.ckpt" 
