ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 64
  resolution: 64 
  scale: 64
  r: 1.1
  ect_type: "points"
  ambient_dimension: 2
  normalized: True

modelconfig:
  module: models.vae
  in_channels: 1
  latent_dim: 64
  learning_rate: 0.001
  ectconfig: *ref-ectconfig

data: 
  module: datasets.mnist
  root: "./data/mnistpointcloud"
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  num_pts: 128
  ectconfig: *ref-ectconfig

trainer:
  accelerator: auto
  max_epochs: 1
  log_every_n_steps: 1
  save_dir: ./trained_models 
  experimentname: vae_mnist
  model_name: "vae_mnist.ckpt"


loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "vae_mnist"
  tags: []
