ectconfig: &ref-ectconfig
  seed: 2024
  num_thetas: 256
  resolution: 256 
  scale: 128
  r: 5
  ect_type: "points"
  ambient_dimension: 3
  normalized: True

data: 
  module: datasets.shapenetcore
  root: ./data/shapenet
  cates: 
    - chair
  num_workers: 0
  batch_size: 64
  pin_memory: True
  drop_last: False
  force_reload: False
  ectconfig: *ref-ectconfig

modelconfig:
  module: models.vae
  in_channels: 1
  latent_dim: 256
  learning_rate: 0.000005
  ectconfig: *ref-ectconfig 

trainer:
  accelerator: auto
  max_epochs: 100 # Was 1000 before.
  log_every_n_steps: 1
  save_dir: ./trained_models 
  model_name: vae_chair.ckpt

loggers: 
  logger: wandb
  project: shape-synthesis
  entity: aidos-labs
  save_dir: ./lightning_logs
  experiment_name: "vae_chair"
  tags: []