data:
  batch_size: 16
  cates:
  - chair
  drop_last: false
  ectconfig:
    ambient_dimension: 3
    ect_type: points
    normalized: true
    num_thetas: 8
    r: 5
    resolution: 8
    scale: 1
    seed: 2024
  force_reload: false
  module: datasets.shapenetcore
  num_pts: 2048
  num_workers: 0
  pin_memory: true
  root: ./data/shapenet
render:
  dataset_name: chair
  ectconfig:
    ambient_dimension: 3
    ect_type: points
    normalized: true
    num_thetas: 32
    r: 5
    resolution: 32
    scale: 16
    seed: 2024
  experiment_name: 32_16_chair
  num_epochs: 2000
  num_pts: 2048
